### ISSUE TITLE
Improving the "Testing Solid" document

### ISSUE THREAD

**Issue by faassen** [solidjs/solid-docs-legacy#135]
I tried to follow the "Testing Solid" document. Unfortunately I couldn't get either Jest nor Vitest to work following its instructions. After a while I discovered that templates for `ts-vitest` and `ts-uvu` existed. `ts-vitest` is also broken in apparently the same way as the instructions. `ts-uvu` works (though its behavior when a test fails is undesirable, pages of source code are emitted).

The `ts-jest` information didn't work for me either. I've since tweaked things until they worked, and contributed a new template `ts-jest`: https://github.com/solidjs/templates/pull/48

It strikes me that maintaining this information in templates is better than documenting everything in (broken) docs. The documentation can tell people to use the templates, and focus on explaining how to write tests.

That leaves ``vitest`; I can't get it to work at present. Until it's fixed I propose we don't mention vitest in the documentation. After that it's easy enough to restore, as it's very similar to the way jest is used.

If people are okay with this plan I can go ahead and contribute some edits.

**Comment by Jutanium** [comment]
I agree. Go ahed and submit that PR, and we'll keep the holistic vision (provide templates and examples as the basis) in the new docs site.
