### ISSUE TITLE
directory name for Japanese docs

### ISSUE THREAD

**Issue by jay-es** [solidjs/solid-docs-legacy#14]
Japanese documents are now in `jp` directory.
It's the country code for Japan.
And the language code for Japanese is `ja`.
(It's confusing!)
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

It might be a good idea to rename the directory sometime.

**Comment by davedbase** [comment]
Oh wow! That's my mistake I legitimately thought it was ja. I'll change it right now. Thanks for pointing it out!

**Comment by jay-es** [comment]
@davedbase Thank you for your quick response!
Please do the same for the `solid-site` repository sometime.

**Comment by davedbase** [comment]
Yup, already done and deployed to production. Apologies for that. You did originally have it as ja but I thought I was being more accurate with jn. I hope you stick around. We would love to get the tutorials and the website translated, but I know it may be a lot to ask of you. We'd be so grateful though! =)
