### ISSUE TITLE
Indonesian Translation 🇮🇩

### ISSUE THREAD

**Issue by athif23** [solidjs/solid-docs-legacy#16]

**Comment by davedbase** [comment]
@athif23 thank you so much for this. I can't wait to get it live on the Solid site. There are tutorials remaining but those are individually short, there are just many of them. Also the website could use a translation: https://github.com/solidjs/solid-site/tree/i18n/lang

Didn't take me more than an hour or two to get them done. Would be so appreciative if you had a moment for those =)

**Comment by athif23** [comment]
@davedbase I can try to work on the website translation https://github.com/solidjs/solid-site/tree/i18n/lang. I don't really know about the tutorials, but let's just see if I can have some time for them.

**Comment by davedbase** [comment]
@athif23 the website translation would be more helpful than tutorials, because of the marketing element of it.

**Comment by athif23** [comment]
@davedbase Okay, working on it right now just one question though, why can't I find the `lang` folder in the main branch? I'm a bit confused on where do I start to translate.

**Comment by davedbase** [comment]
Oh amazing. Everything is in the i18n branch because we're working on this as a future upgrade to the site.

**Comment by athif23** [comment]
@davedbase just finished working on them https://github.com/solidjs/solid-site/pull/132, they are ready to be merged.
