### ISSUE TITLE
Missing word(s) in migration advice

### ISSUE THREAD

**Issue by EvAvKein** [solidjs/solid-docs-legacy#175]
In Solid's [advice for migrating from React](https://www.solidjs.com/guides/comparison#advice-for-migrating), the first paragraph ends with:
> Instead of thinking of function components as the render function, think of them as a .

With DevTools I can see that there's an empty `<code>` element at the end of that sentence.

...I couldn't find that page/text in this repo (or other Solid ones), so let me know if there's a more appropriate repo for the issue

**Comment by davedbase** [comment]
Thanks for letting us know!

**Comment by davedbase** [comment]
Thanks for letting us know. @Jutanium heads up.

**Comment by Jutanium** [comment]
@modderme123 At this point you understand the compilation more than I do, any thoughts?

**Comment by milomg** [comment]
I would finish that with a creation function (constructor)

**Comment by edemaine** [comment]
I believe there is one in the source. The issue is that the Markdown compilation isn't outputting it. (Something about backquotes at the end of a paragraph?)

**Comment by tv42** [comment]
Duplicate of #165
