### ISSUE TITLE
Mistype in documentation

### ISSUE THREAD

**Issue by lishine** [solidjs/solid-docs-legacy#193]
### Describe the bug

missing a word

### Your Example Website or App

.

### Steps to Reproduce the Bug or Issue

1

### Expected behavior

.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/6741645/192462565-ab97aa10-26a1-45a2-a2e5-3e1cd5b82109.png)

### Platform

Linux

**Comment by ghost** [comment]
Hello, I'm interested in this issue. I see it is missing a word after "a" in the screenshot. What word would you want added?

**Comment by lishine** [comment]
Setup function / configuration function ?
😄
Maybe the best to do is to ask the one who wrote the sentence 😁

**Comment by mpeg** [comment]
The word should be `constructor` – this actually seems to be an issue with the MDX parser, maybe it's somehow executing it as code so it ends up being an Object (as in, the constructor of the MDXContent?)

Either way, an easy fix would be to add a space to the word within the backticks like \` constructor\` which won't make a difference to the display of it, but will fix the issue 

I went ahead and created a pull request #202 with that fix, but feel free to close it if you want to fix a better way of fix upstream somehow.

**Comment by mpeg** [comment]
Any other property names on backticks seem to make it either resolve them or crash (e.g. `hasOwnProperty` will throw and `toString` renders `[object Undefined]`)

I suppose would be good to open an issue on the library doing the markdown parsing and reference this one

**Comment by edemaine** [comment]
Fixed by #194
