### ISSUE TITLE
Add French translation 🇫🇷

### ISSUE THREAD

**Issue by excessivecoding** [solidjs/solid-docs-legacy#20]
I've started the French translation, as you commented @davedbase it was a bit harder than expected 😅

Help always welcome, of course, and I will put out a few tricky translations I had issue with below, if any french is coming by, feedback are welcome:

- "Fined-grained reactivity" was translated to "Réactivité de précision"
- "Building blocks" was translated to "Pilliers de fondation"
- "tracked" was translated to "surveiller" (but it sounds weird)

Edit: Changed "Réactivité detaillée" for "Réactivité de précision" (still sounds a little weird but better than before)

# TODO

- [x] getting-started.md
- [x] reactivity.md
- [x] rendering.md
- [x] server.md
- [x] api.md
- [x] comparaison.md
- [x] faq.md

**Comment by davedbase** [comment]
@xstevenyung haha oh man. I think I pretty much butchered a lot of the programming context in mine. I asked 2-3 programmers who speak it to go through and adapt the language in a better way.

@amoutonbrady on our core team is Parisian though. I'm sure he'll have a look and give feedback on the translations you go along =)

**Comment by lukechu10** [comment]
Je pense que "fondation" tout seul est mieux que "pillers de fondation". Ca se dit "pilliers de fondation"?
"Fine-grained reactivity" pourrait être "réactivité à grain fin" mais je ne sais pas si c'est meilleur que ce que tu as déjà.

**Comment by excessivecoding** [comment]
@lukechu10 Je pense que le contexte est important pour le coup, voilà là où je l'ai utilisé:

```
Les deux principaux piliers de ces fondations sont les Composants et les Primitives Réactives.
```

J'ai l'impression que c'est pas très français pour le coup, qu'est ce que tu en penses ?


Pour "Fine-grained reactivity", je ne sais vraiment pas, "réactivité à grain fin" ça reste très vague alors que le terme "fined-grained" est assez explicite en anglais. Assez compliqué pour celui-là surtout que c'est un peu le terme d'accroche de la lib.

**Comment by MidouWebDev** [comment]
Salut, j'aimerais bien vous aider à traduire ces fichiers.

**Comment by excessivecoding** [comment]
> Salut, j'aimerais bien vous aider à traduire ces fichiers.

Hello @MidouWebDev , merci pour ta proposition d'aide. Tu peux prendre le fichier FAQ ou comparaison si tu veux et faire une PR sur la branche 👍

Edit: Je ne sais pas trop comment ça se passe pour combiner différentes PR de plusieurs auteurs, si tu rencontres des difficultés, n'hésite pas à me contacter sur Discord xstevenyung#6357 ou sur le serveur discord officiel de Solid.

**Comment by MidouWebDev** [comment]
Ok, can you send me the discord link please

**Comment by davedbase** [comment]
Merci à vous deux pour votre contribution. @MidouWebDev le Discord est disponible sur https://discord.com/invite/solidjs

**Comment by excessivecoding** [comment]
All done for the initial translation @davedbase @amoutonbrady 🎉🇫🇷

Might be good to have someone reread if possible.

**Comment by amoutonbrady** [comment]
Awesome work, I've left some comments on the PR without even realizing there was an issue open 🤦🏻‍♂️ 

I'll try to find the time in the upcoming week to have it read and probably use my handy little [auto correct software](https://www.antidote.info/) to see if there's some stuff that can be added here and there. Although, from what I've seen the translations are in really good shape already :)

**Comment by amoutonbrady** [comment]
I started a new PR #31  with some fixes as a I go and pass over files. I wouldn't mind a second pair of eyes @xstevenyung if you have some time to kill to make sure I didn't click the auto correct a bit too quickly.

In any case thanks again 🙏🏻

**Comment by davedbase** [comment]
I believe we still be missing the two remaining md files. @MidouWebDev will you have a chance to tackle those for us? If not maybe @xstevenyung you have a few spare minutes for us (again)?

**Comment by excessivecoding** [comment]
Yeah I could do this if we need 👍

**Comment by excessivecoding** [comment]
@davedbase any news on this ? I might have some spare time this week but maybe we would rather wait for @MidouWebDev ?

**Comment by davedbase** [comment]
I went ahead and merged the current French PR. It seems like @MidouWebDev has disappeared on us so I'll say yes @xstevenyung if you have the time I'd really appreciate the contribution. :-) we can't hold up French, German, Russian and other langs are coming in hot.
