### ISSUE TITLE
`children.toArray` is missing from the docs

### ISSUE THREAD

**Issue by ryansolid** [solidjs/solid-docs-legacy#257]
We added a shorthand to help with managing arrays with the children helper. It was added in 1.5 but I appear to have missed adding it to the docs. https://github.com/solidjs/solid/releases/tag/v1.5.0

**Comment by edemaine** [comment]
Actually, it looks like you added it back in August 2022: https://github.com/solidjs/solid-docs/commit/ea87ff1fc622bcca75dbf7b27423c7bdd3bfd136

The entry for `children` is long so maybe it is just hard to see?
