### ISSUE TITLE
Avoid wording that reflects a subjective evaluation on the user

### ISSUE THREAD

**Issue by syahzuan** [solidjs/solid-docs-legacy#268]
This is regarding the [document ](https://github.com/solidjs/solid-docs/blob/main/langs/en/tutorials/flow_show/lesson.md) at tutorials/flow_show/lesson.md.

> JSX allows you to use JavaScript to control the logic flow in the templates. However, without a Virtual DOM, naive use of things like `Array.prototype.map` would wastefully recreate all the DOM nodes on every update.

I think words like wasteful/expensive recreation are great because they objectively describe good practices. But a word like "**_naive_** use of things" can sound like a subjective evaluation on the user (i.e. the user's level of knowledge is naive).

I suggest removing the word naive from the sentence.

> JSX allows you to use JavaScript to control the logic flow in the templates. However, without a Virtual DOM, ~~naive~~ use of things like `Array.prototype.map` would wastefully recreate all the DOM nodes on every update.

It sounds more neutral, and the message is not compromised since the word "wastefully" is sufficient to highlight the downside of this use.

I am new to docs contribution, so kindly ignore this if it sounds like nitpicking trivial details hehe. Happy to open a PR if this suggestion helps. 

Cheers.

**Comment by edemaine** [comment]
Seems reasonable to me. Yes, please make a PR.
