### ISSUE TITLE
Chinese translations of frontmatter data

### ISSUE THREAD

**Issue by davedbase** [solidjs/solid-docs-legacy#3]
@Gavin-Gong we recently added Frontmatter to the Docs to help with sorting + controlling titling on the Solid website. If you have a moment would you mind translating the titles and descriptions for us? We're very close to getting the translations up on the website! =)

**Comment by Gavin-Gong** [comment]
Looking forward to the translation up on the website 😁

**Comment by davedbase** [comment]
@Gavin-Gong yup we have it staged at https://dev.solidjs.com/. Click the dropdown! =) Just waiting on Japanese to push live I think.
