### ISSUE TITLE
Explanation of createStore functionality is difficult to read

### ISSUE THREAD

**Issue by primos63** [solidjs/solid-docs-legacy#35]
The explanation of `createStore`'s functionality is 
> This creates a tree of Signals as proxy that allows individual values in nested data structures to be independently tracked.
>
As-is the sentence is difficult to read. It's missing an `a` before `proxy` and the use of independently seems to be redundant. How else would individual values be tracked?

This should read as 
> This creates a tree of Signals as a proxy that allows individual values in nested data structures to be tracked.
>
or 
> This creates a tree of Signals as a proxy that allows values in nested data structures to be independently tracked.

**Comment by davedbase** [comment]
Thanks for the clarification :-)
