### ISSUE TITLE
Add Russian Translations

### ISSUE THREAD

**Issue by ghost** [solidjs/solid-docs-legacy#37]
I've translated the docs.

Checkout PR #36  for more information.

**Comment by davedbase** [comment]
This is absolutely fantastic! Thank you. I hate to request on the heals of such a big contribution but if you have a moment we could use the help translating the website (not a big project actually quite easy) as well as tutorials. Our tutorials are extremely long though and that would be quite an ask.

Either way this is an amazing addition for us. Thank you from the whole community!

**Comment by ghost** [comment]
No problem. 

Helping projects makes me happy and a part of something. I will translate the guides as well slowly, but surely. 

When it comes to Solid, I use it as a daily driver and I see the feature in it.

**Comment by davedbase** [comment]
Thanks again!
