### ISSUE TITLE
Duplicates in FAQ section

### ISSUE THREAD

**Issue by ghost** [solidjs/solid-docs-legacy#46]
👇🏻 Why is the word _TypeScript_ repeated three times? 

## I really dislike JSX, any chance of a Template DSL? Oh, I see you have Tagged Template Literals/HyperScript. Maybe I will use those...

.... 
**It's good to have options, but Solid's JSX is really the best solution here. A Template DSL would be great as well, albeit more 
restrictive, but JSX gives us so much for free. `TypeScript`, Existing Parsers, Syntax Highlighting, `TypeScript`, Prettier, Code
Completion, and last and not least `TypeScript`.**
....

https://www.solidjs.com/docs/latest/api#6.-i-really-dislike-jsx%2C-any-chance-of-a-template-dsl%3F-oh%2C-i-see-you-have-tagged-template-literals%2Fhyperscript.-maybe-i-will-use-those...

**Comment by davedbase** [comment]
lol...you know what I've read this line 4 times in the past and didn't catch that. For a second here I thought it was a joke to reinforce TS support but I don't think so. Good catch! @Jutanium when we get a chance we should clean that up.

**Comment by ghost** [comment]
XD

**Comment by edemaine** [comment]
Honestly, I thought it was a (funny) joke when I read it. From what I've read, Svelte and other DSLs have struggled for a long time to get decent TypeScript support, and the point is that this makes it easy.

I think it's fine as is. But also don't feel strongly about it.

**Comment by ghost** [comment]
:)
