### ISSUE TITLE
Certain Docs sections may be better placed under Getting Started

### ISSUE THREAD

**Issue by bobaekang** [solidjs/solid-docs-legacy#50]
Currently, the Docs page sections are more or less API documentations--even the page URL is `/docs/latest/api`--except for the last two sections: "Comparison with other libraries" and "FAQ". On the other hand, the Getting Started page features more high-level concepts and explanations in general.

Given that, I'd like to suggest moving these two sections ("Comparison with other libraries" and "FAQ") to the Getting Started page.

**Comment by davedbase** [comment]
Moved the issue to solid-docs as the structure is defined by the markdown files in this repository. I'm in agreement about this however I'll leave the final say to @Jutanium

**Comment by Jutanium** [comment]
@davedbase We're good with making these kind of changes without worrying about translations, right?

**Comment by davedbase** [comment]
That is correct. Just a matter of moving the sections from one file to another. It's painful will only take me an hour I'd imagine.

**Comment by Jutanium** [comment]
There are a few related issues here - only some of the sections on the `/guide` route are actually about Getting Started, but that is the label it gets in the menu. If we make this change, how about changing the title from "Getting Started" to "Guide", and changing "Docs" to "Reference" (or "API")?
