### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by lechuckroh** [solidjs/solid-docs-legacy#78]
Korean translation after PR( #77 )

- Guide
  - [x] Comparison
  - [x] FAQ
  - [x] Getting Started
  - [x] Reactivity
  - [x] Rendering
  - [x] Server
  - [x] Testing
  - [x] TypeScript
- API
  - [x] Basic Reactivity
  - [x] Lifecycles
  - [x] Reactive Utilities
  - [x] Stores
  - [x] Component APIs
  - [x] Secondary Primitives
  - [x] Rendering
  - [x] Control Flow
  - [x] Special JSX Attributes
- Tutorial
  - [x] async_lazy
  - [x] async_resources
  - [x] async_suspense
  - [x] async_suspense_list
  - [x] async_transitions
  - [x] bindings_classlist
  - [x] bindings_directives
  - [x] bindings_events
  - [x] bindings_forward_refs
  - [x] bindings_refs
  - [x] bindings_spreads
  - [x] bindings_style
  - [x] directory.json
  - [x] flow_dynamic
  - [x] flow_error_boundary
  - [x] flow_for
  - [x] flow_index
  - [x] flow_portal
  - [x] flow_show
  - [x] flow_switch
  - [X] introduction_basics
  - [x] introduction_components
  - [x] introduction_derived
  - [x] introduction_effects
  - [x] introduction_jsx
  - [x] introduction_memos
  - [x] introduction_signals
  - [x] lifecycles_oncleanup
  - [x] lifecycles_onmount
  - [x] props_children
  - [x] props_defaults
  - [x] props_split
  - [x] reactivity_batch
  - [x] reactivity_on
  - [x] reactivity_untrack
  - [x] stores_context
  - [x] stores_createstore
  - [x] stores_immutable
  - [x] stores_mutation
  - [x] stores_nested_reactivity
  - [x] stores_nocontext

**Comment by davedbase** [comment]
Hey! Just checking in how this is going :-) looks like you made amazing progress.

**Comment by lechuckroh** [comment]
@davedbase 
Hi.. 
I'm translating one or two tutorials every day, I hope I can send tutorual PR in about a week hopefully. 😀
